[package]
name = "pkg-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
serde_yaml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.9"
flate2 = "1.0.22"
